import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import MainBody from "@/components/Main";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Google Meet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <MainBody/>
      </main>
    </>
  );
}
